version: '3'

services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
  web:
    build: ./imperial_city_beef
    volumes:
      - ./imperial_city_beef/:/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  pgdata:      